services:
  db:
    image: mysql:8.0
    container_name: my_mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: ${DB_HOST}
      MYSQL_DATABASE: ${DB_DATABASE}
      TZ: Asia/Shanghai
    command: --default-time-zone='+08:00'
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.2
    container_name: my_redis
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    command: ['redis-server', '--port', '${REDIS_PORT}']
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
